//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NumbersTranslatorToPortuguese.NumberTranslatorWebService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="NumberTranslatorWebService.INumbersTranslatorWebService")]
    public interface INumbersTranslatorWebService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INumbersTranslatorWebService/TranslateText", ReplyAction="http://tempuri.org/INumbersTranslatorWebService/TranslateTextResponse")]
        string[][] TranslateText(string text);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INumbersTranslatorWebService/TranslateText", ReplyAction="http://tempuri.org/INumbersTranslatorWebService/TranslateTextResponse")]
        System.Threading.Tasks.Task<string[][]> TranslateTextAsync(string text);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface INumbersTranslatorWebServiceChannel : NumbersTranslatorToPortuguese.NumberTranslatorWebService.INumbersTranslatorWebService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class NumbersTranslatorWebServiceClient : System.ServiceModel.ClientBase<NumbersTranslatorToPortuguese.NumberTranslatorWebService.INumbersTranslatorWebService>, NumbersTranslatorToPortuguese.NumberTranslatorWebService.INumbersTranslatorWebService {
        
        public NumbersTranslatorWebServiceClient() {
        }
        
        public NumbersTranslatorWebServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public NumbersTranslatorWebServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public NumbersTranslatorWebServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public NumbersTranslatorWebServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string[][] TranslateText(string text) {
            return base.Channel.TranslateText(text);
        }
        
        public System.Threading.Tasks.Task<string[][]> TranslateTextAsync(string text) {
            return base.Channel.TranslateTextAsync(text);
        }
    }
}
